inventory2: inventory2.o read_line.o
	gcc -o inventory2 inventory2.o read_line.o

inventory2.o: inventory2.c read_line.h
	gcc -c inventory2.c

read_line.o: read_line.c read_line.h
	gcc -c read_line.c
